In [1]:
import pandas as pd 
import numpy as np
import time

In [71]:
result_df = pd.read_csv('./data/result_df.csv', encoding='utf-8') 
result_df

         평균     평년  year  month  day
0     1,287  1,561  2015      1    2
1     1,287  1,449  2015      1    5
2     1,303  1,432  2015      1    6
3     1,277  1,411  2015      1    7
4     1,352  1,407  2015      1    8
5     1,333  1,403  2015      1    9
6     1,329  1,352  2015      1   12
7     1,329  1,340  2015      1   13
8     1,329  1,326  2015      1   14
9     1,262  1,321  2015      1   15
10    1,258  1,314  2015      1   16
11    1,253  1,268  2015      1   19
12    1,262  1,254  2015      1   20
13    1,254  1,239  2015      1   21
14    1,233  1,222  2015      1   22
15    1,241  1,216  2015      1   23
16    1,228  1,221  2015      1   26
17    1,212  1,231  2015      1   27
18    1,199  1,241  2015      1   28
19    1,203  1,239  2015      1   29
20    1,203  1,251  2015      1   30
21    1,210  1,241  2015      2    2
22    1,214  1,238  2015      2    3
23    1,213  1,238  2015      2    4
24    1,261  1,239  2015      2    5
25    1,256  1,240  2015      2    6
26    1,261  1,231  2015      2    9
27    1,248  1,229  2015      2   10
28    1,248  1,226  2015      2   11
29    1,204  1,222  2015      2   12
...     ...    ...   ...    ...  ...
1158  2,538  1,527  2019     11   18
1159  2,503  1,524  2019     11   19
1160  2,511  1,523  2019     11   20
1161  2,508  1,523  2019     11   21
1162  2,556  1,524  2019     11   22
1163  2,533  1,527  2019     11   25
1164  2,533  1,529  2019     11   26
1165  2,522  1,525  2019     11   27
1166  2,504  1,521  2019     11   28
1167  2,504  1,517  2019     11   29
1168  2,526  1,522  2019     12    2
1169  2,546  1,527  2019     12    3
1170  2,554  1,531  2019     12    4
1171  2,556  1,533  2019     12    5
1172  2,583  1,575  2019     12    9
1173  2,678  1,589  2019     12   10
1174  2,764  1,680  2019     12   11
1175  2,866  1,714  2019     12   12
1176  2,911  1,750  2019     12   13
1177  2,972  2,042  2019     12   16
1178  2,992  1,861  2019     12   17
1179  3,021  1,856  2019     12   18
1180  3,055  1,854  2019     12   19
1181  3,049  1,817  2019     12   20
1182  3,082  1,609  2019     12   23
1183  3,073  1,618  2019     12   24
1184  3,068  1,596  2019     12   26
1185  3,022  1,582  2019     12   27
1186  2,987  1,480  2019     12   30
1187  3,023  1,473  2019     12   31

[1188 rows x 5 columns]

In [75]:
moo = pd.read_excel('./data/2015_01_03.xlsx', encoding= 'utf-8')
moo

,구분,Unnamed: 1,Unnamed: 2,2020-01-02 00:00:00,2020-01-05 00:00:00,2020-01-06 00:00:00,2020-01-07 00:00:00,2020-01-08 00:00:00,2020-01-09 00:00:00,2020-01-12 00:00:00,...,2020-03-18 00:00:00,2020-03-19 00:00:00,2020-03-20 00:00:00,2020-03-23 00:00:00,2020-03-24 00:00:00,2020-03-25 00:00:00,2020-03-26 00:00:00,2020-03-27 00:00:00,2020-03-30 00:00:00,2020-03-31 00:00:00
0,평균,NaN,NaN,"1,287","1,287","1,303","1,277","1,352","1,333","1,329",...,"1,260","1,257","1,239","1,261","1,261","1,250","1,297","1,283","1,283","1,286"
1,평년,NaN,NaN,"1,561","1,449","1,432","1,411","1,407","1,403","1,352",...,"1,297","1,305","1,310","1,304","1,300","1,298","1,295","1,290","1,287","1,298"
2,서울,경동,가을,"1,500","1,500","1,500",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
3,NaN,NaN,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
4,NaN,복조리,가을,"1,500","1,500","1,500",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
5,NaN,NaN,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
6,NaN,영등포,가을,"2,000","2,000","2,000",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
7,NaN,NaN,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
8,NaN,A-유통,월동,"1,350","1,350","1,350","1,350","1,350","1,350","1,350",...,"1,200","1,200","1,200","1,200","1,200","1,200","1,400","1,400","1,400","1,400"
9,NaN,B-유통,월동,"1,180","1,180","1,180","1,180","1,180","1,180","1,280",...,"1,280","1,280",880,"1,280","1,280","1,280","1,280","1,180",990,990
10,NaN,C-유통,월동,"1,280","1,280","1,280","1,280","1,280","1,280","1,280",...,"1,280","1,280","1,280","1,280","1,280","1,280","1,280","1,280","1,280","1,280"
11,NaN,E-유통,월동,"1,000","1,000","1,000","1,000","1,350","1,350","1,350",...,"1,150","1,150","1,150","1,150","1,150","1,150","1,180","1,180","1,180","1,180"
12,NaN,F-유통,월동,"1,000","1,000","1,000","1,000","1,350","1,350","1,350",...,"1,150","1,150","1,150","1,150","1,150","1,150","1,200","1,200","1,200","1,200"
13,부산,부전,가을,800,800,800,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
14,NaN,NaN,월동,"1,000","1,000","1,000","1,000","1,000","1,000","1,000",...,"1,000","1,000","1,000","1,000","1,000","1,000","1,000","1,000","1,000","1,000"
15,NaN,A-유통,월동,"1,350","1,350","1,350","1,350","1,350","1,350","1,350",...,"1,200","1,200","1,200","1,200","1,200","1,200","1,400","1,400","1,200","1,200"
16,NaN,D-유통,월동,790,790,"1,280","1,280","1,280","1,280","1,280",...,"1,180","1,180",980,980,980,980,"1,180","1,180","1,180","1,180"
17,대구,동구,가을,"1,500","1,500","1,500",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
18,NaN,NaN,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,400","1,400","1,400","1,400","1,400","1,400","1,400","1,400","1,400","1,400"
19,NaN,A-유통,월동,"1,350","1,350","1,350","1,350","1,350","1,350","1,350",...,-,-,-,-,-,-,-,-,-,-
20,NaN,C-유통,월동,"1,280","1,280","1,280","1,280","1,280","1,280","1,280",...,"1,180","1,180","1,180","1,180","1,180","1,180","1,280","1,280","1,280","1,280"
21,인천,현대,가을,"1,500","1,500","1,500",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
22,NaN,NaN,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
23,NaN,E-유통,월동,"1,000","1,000","1,000","1,000","1,350","1,350","1,350",...,"1,150","1,150","1,150","1,150","1,150","1,150","1,200","1,200","1,200","1,200"
24,광주,양동,가을,"1,000","1,000","1,000",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
25,NaN,NaN,월동,"1,500","1,500","1,500","1,000","1,000","1,000","1,000",...,"1,000","1,000","1,000","1,000","1,000","1,000","1,000","1,000","1,000","1,000"
26,NaN,C-유통,월동,"1,180","1,180","1,180","1,180","1,350","1,350","1,180",...,"1,180","1,180","1,180","1,180","1,180","1,180","1,280","1,180","1,180","1,280"
27,대전,역전,가을,"1,100","1,100","1,400",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
28,NaN,NaN,월동,-,-,-,"1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,400","1,400","1,300","1,300","1,200","1,200","1,200"
29,NaN,C-유통,월동,"1,180","1,180","1,180","1,180","1,350","1,350","1,350",...,"1,180","1,180","1,180","1,180","1,180","1,180","1,280","1,280","1,280","1,280"
30,NaN,E-유통,월동,"1,000","1,000","1,000","1,000","1,350","1,350","1,350",...,"1,150","1,150","1,150","1,150","1,150","1,150","1,180","1,180","1,180","1,180"
31,울산,신정,월동,"1,500","1,500","1,500","1,500","1,500","1,160","1,160",...,"1,160","1,160","1,160","1,160","1,160","1,160","1,160","1,160","1,160","1,160"
32,NaN,A-유통,월동,"1,350","1,350","1,350","1,350","1,350","1,350","1,350",...,"1,200","1,200","1,200","1,200","1,200","1,200","1,400","1,400","1,400","1,400"
33,수원,지동,가을,"1,500","1,500","1,500",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
34,NaN,NaN,월동,"1,250","1,250","1,250","1,250","1,250","1,250","1,250",...,"1,250","1,330","1,330","1,330","1,330","1,330","1,330","1,330","1,330","1,330"
35,NaN,B-유통,월동,"1,150","1,150","1,150","1,150",-,-,"1,250",...,"1,250","1,250","1,200","1,250","1,250","1,250","1,250",990,"1,200","1,200"
36,의정부,A-유통,월동,"1,350","1,350","1,350","1,350",-,-,-,...,"1,200","1,300","1,300","1,300","1,300","1,300","1,400","1,400","1,400","1,400"
37,춘천,중앙,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
38,NaN,E-유통,월동,"1,000","1,000","1,000","1,000","1,350","1,350","1,350",...,"1,150","1,150","1,150","1,150","1,150","1,150","1,200","1,200","1,200","1,200"
39,청주,육거리,가을,"1,500","1,500","1,500",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
40,NaN,NaN,월동,"1,300","1,300","1,300","1,430","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
41,NaN,B-유통,월동,"1,250","1,250","1,250","1,250","1,250","1,250","1,250",...,"1,280",990,990,"1,280","1,280",990,990,990,"1,280","1,280"
42,전주,남부,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
43,NaN,C-유통,월동,"1,280","1,280","1,280","1,280","1,480","1,480","1,480",...,-,-,-,-,-,-,-,-,-,-
44,순천,A-유통,월동,-,-,-,-,-,-,-,...,"1,200","1,200","1,200","1,200","1,200","1,200","1,400","1,400","1,200","1,200"
45,포항,죽도,월동,"1,500","1,500","1,500","1,500","1,500","1,160","1,160",...,"1,160","1,160","1,160","1,160","1,160","1,160","1,160","1,160","1,160","1,160"
46,NaN,E-유통,월동,"1,000","1,000","1,000","1,000","1,350","1,350","1,350",...,"1,150","1,150","1,150","1,150","1,150","1,150","1,200","1,200","1,200","1,200"
47,안동,C-유통,월동,"1,180","1,180","1,180","1,180","1,180","1,180","1,180",...,"1,180","1,180","1,180","1,180","1,180","1,180","1,180","1,180","1,280","1,280"
48,창원,상남,가을,"1,000","1,000","1,000",-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
49,NaN,NaN,월동,"1,500","1,500","1,500","1,500","1,500","1,500","1,500",...,"1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500","1,500"
50,NaN,C-유통,월동,"1,350","1,350","1,350","1,350","1,350","1,350","1,350",...,"1,180","1,180","1,150","1,150","1,150","1,150","1,280","1,280","1,280","1,280"
51,제주,동문,월동,"1,000","1,000","1,000","1,000","1,000","1,000","1,000",...,"1,160","1,160","1,160","1,330","1,330","1,330","1,330","1,330","1,330","1,330"
52,NaN,C-유통,가을,"1,280","1,280",-,-,-,-,-,...,-,-,-,-,-,-,-,-,-,-
53,NaN,NaN,월동,-,-,"1,280","1,280","1,280","1,280","1,280",...,"1,180","1,180","1,180","1,180","1,180","1,180","1,180","1,180","1,180","1,180"

In [ ]:
moo.fillna(0)

In [73]:
moo.T

,0,1,2,3,4,5,6,7,8,9,...,44,45,46,47,48,49,50,51,52,53
구분,평균,평년,서울,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,순천,포항,NaN,안동,창원,NaN,NaN,제주,NaN,NaN
Unnamed: 1,NaN,NaN,경동,NaN,복조리,NaN,영등포,NaN,A-유통,B-유통,...,A-유통,죽도,E-유통,C-유통,상남,NaN,C-유통,동문,C-유통,NaN
Unnamed: 2,NaN,NaN,가을,월동,가을,월동,가을,월동,월동,월동,...,월동,월동,월동,월동,가을,월동,월동,월동,가을,월동
2020-01-02 00:00:00,"1,287","1,561","1,500","1,500","1,500","1,500","2,000","1,500","1,350","1,180",...,-,"1,500","1,000","1,180","1,000","1,500","1,350","1,000","1,280",-
2020-01-05 00:00:00,"1,287","1,449","1,500","1,500","1,500","1,500","2,000","1,500","1,350","1,180",...,-,"1,500","1,000","1,180","1,000","1,500","1,350","1,000","1,280",-
2020-01-06 00:00:00,"1,303","1,432","1,500","1,500","1,500","1,500","2,000","1,500","1,350","1,180",...,-,"1,500","1,000","1,180","1,000","1,500","1,350","1,000",-,"1,280"
2020-01-07 00:00:00,"1,277","1,411",-,"1,500",-,"1,500",-,"1,500","1,350","1,180",...,-,"1,500","1,000","1,180",-,"1,500","1,350","1,000",-,"1,280"
2020-01-08 00:00:00,"1,352","1,407",-,"1,500",-,"1,500",-,"1,500","1,350","1,180",...,-,"1,500","1,350","1,180",-,"1,500","1,350","1,000",-,"1,280"
2020-01-09 00:00:00,"1,333","1,403",-,"1,500",-,"1,500",-,"1,500","1,350","1,180",...,-,"1,160","1,350","1,180",-,"1,500","1,350","1,000",-,"1,280"
2020-01-12 00:00:00,"1,329","1,352",-,"1,500",-,"1,500",-,"1,500","1,350","1,280",...,-,"1,160","1,350","1,180",-,"1,500","1,350","1,000",-,"1,280"
2020-01-13 00:00:00,"1,329","1,340",-,"1,500",-,"1,500",-,"1,500","1,350","1,280",...,-,"1,160","1,350","1,180",-,"1,500","1,350","1,000",-,"1,280"
2020-01-14 00:00:00,"1,329","1,326",-,"1,500",-,"1,500",-,"1,500","1,350","1,280",...,-,"1,160","1,350","1,180",-,"1,500","1,350","1,000",-,"1,280"
2020-01-15 00:00:00,"1,262","1,321",-,"1,500",-,"1,500",-,"1,500","1,300","1,280",...,-,"1,160","1,350",980,-,"1,500",980,"1,000",-,980
2020-01-16 00:00:00,"1,258","1,314",-,"1,500",-,"1,500",-,"1,500","1,300","1,100",...,-,"1,160","1,350",980,-,"1,500",980,"1,000",-,980
2020-01-19 00:00:00,"1,253","1,268",-,"1,500",-,"1,500",-,"1,500","1,300","1,180",...,-,"1,160","1,350",980,-,"1,500",980,"1,000",-,980
2020-01-20 00:00:00,"1,262","1,254",-,"1,500",-,"1,500",-,"1,500","1,300","1,180",...,-,"1,160","1,350",980,-,"1,500",980,"1,000",-,980
2020-01-21 00:00:00,"1,254","1,239",-,"1,500",-,"1,500",-,"1,500","1,300","1,180",...,-,"1,160","1,350",980,-,"1,500",980,"1,000",-,980
2020-01-22 00:00:00,"1,233","1,222",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,-,"1,160","1,000","1,150",-,"1,500","1,150","1,000",-,980
2020-01-23 00:00:00,"1,241","1,216",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,-,"1,160","1,000","1,150",-,"1,500","1,150","1,000",-,"1,280"
2020-01-26 00:00:00,"1,228","1,221",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,-,"1,160","1,000","1,150",-,"1,500","1,150","1,000",-,"1,280"
2020-01-27 00:00:00,"1,212","1,231",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,"1,100","1,160","1,000","1,150",-,"1,500","1,150","1,000",-,"1,280"
2020-01-28 00:00:00,"1,199","1,241",-,"1,500",-,"1,500",-,"1,500",950,"1,080",...,"1,100","1,160","1,000","1,150",-,"1,500","1,150","1,000",-,"1,280"
2020-01-29 00:00:00,"1,203","1,239",-,"1,500",-,"1,500",-,"1,500",950,"1,080",...,"1,300","1,160","1,000",950,-,"1,500",950,"1,000",-,900
2020-01-30 00:00:00,"1,203","1,251",-,"1,500",-,"1,500",-,"1,500",950,"1,080",...,"1,300","1,160","1,000",950,-,"1,500",950,"1,000",-,900
2020-02-02 00:00:00,"1,210","1,241",-,"1,500",-,"1,500",-,"1,500",950,"1,080",...,"1,300","1,160","1,350",950,-,"1,500",950,"1,000",-,900
2020-02-03 00:00:00,"1,214","1,238",-,"1,500",-,"1,500",-,"1,500",950,"1,080",...,"1,300","1,160","1,350",950,-,"1,500",950,"1,000",-,900
2020-02-04 00:00:00,"1,213","1,238",-,"1,500",-,"1,500",-,"1,500",950,"1,080",...,"1,300","1,160","1,350",950,-,"1,500",950,"1,000",-,900
2020-02-05 00:00:00,"1,261","1,239",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,"1,300","1,160","1,350","1,180",-,"1,500","1,180","1,000",-,950
2020-02-06 00:00:00,"1,256","1,240",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,"1,300","1,160","1,350","1,180",-,"1,500","1,180","1,000",-,950
2020-02-09 00:00:00,"1,261","1,231",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,"1,300","1,160","1,350","1,180",-,"1,500","1,180","1,000",-,950
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-02-13 00:00:00,"1,213","1,227",-,"1,500",-,"1,500",-,"1,500","1,000","1,080",...,"1,000","1,160","1,000","1,250",-,"1,500","1,250","1,000",-,"1,000"
2020-02-16 00:00:00,"1,204","1,270",-,"1,500",-,"1,500",-,"1,500","1,000","1,080",...,"1,000","1,160","1,000","1,250",-,"1,500",990,"1,000",-,"1,000"
2020-02-17 00:00:00,"1,202","1,282",-,"1,500",-,"1,500",-,"1,500","1,000","1,080",...,"1,000","1,160","1,000","1,250",-,"1,500",990,"1,000",-,"1,000"
2020-02-23 00:00:00,"1,205","1,323",-,"1,500",-,"1,500",-,"1,500","1,000","1,180",...,"1,000","1,160","1,580","1,100",-,"1,500","1,000","1,000",-,"1,180"
2020-02-24 00:00:00,"1,212","1,325",-,"1,500",-,"1,500",-,"1,500","1,000","1,380",...,"1,000","1,160","1,580","1,100",-,"1,500","1,000","1,000",-,"1,180"
2020-02-25 00:00:00,"1,229","1,325",-,"1,500",-,"1,500",-,"1,500","1,000",990,...,"1,000","1,160","1,580","1,100",-,"1,500","1,000","1,000",-,"1,180"
2020-02-26 00:00:00,"1,295","1,320",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,000","1,160","1,580","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-02-27 00:00:00,"1,300","1,308",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,000","1,160","1,580","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-02 00:00:00,"1,300","1,281",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,000","1,160","1,580","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-03 00:00:00,"1,297","1,274",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,000","1,160","1,580","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-04 00:00:00,"1,297","1,260",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,000","1,160","1,580","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-05 00:00:00,"1,288","1,247",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,300","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-06 00:00:00,"1,272","1,245",-,"1,500",-,"1,500",-,"1,500","1,300",990,...,"1,300","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-09 00:00:00,"1,286","1,243",-,"1,500",-,"1,500",-,"1,500","1,400",990,...,"1,400","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-10 00:00:00,"1,286","1,246",-,"1,500",-,"1,500",-,"1,500","1,400",990,...,"1,400","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-11 00:00:00,"1,275","1,250",-,"1,500",-,"1,500",-,"1,500","1,400",990,...,"1,400","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-12 00:00:00,"1,246","1,252",-,"1,500",-,"1,500",-,"1,500","1,300","1,080",...,"1,200","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-13 00:00:00,"1,241","1,255",-,"1,500",-,"1,500",-,"1,500","1,200",990,...,"1,200","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-16 00:00:00,"1,248","1,283",-,"1,500",-,"1,500",-,"1,500","1,200",990,...,"1,200","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-17 00:00:00,"1,253","1,288",-,"1,500",-,"1,500",-,"1,500","1,200","1,280",...,"1,200","1,160","1,150","1,180",-,"1,500","1,180","1,000",-,"1,180"
2020-03-18 00:00:00,"1,260","1,297",-,"1,500",-,"1,500",-,"1,500","1,200","1,280",...,"1,200","1,160","1,150","1,180",-,"1,500","1,180","1,160",-,"1,180"
2020-03-19 00:00:00,"1,257","1,305",-,"1,500",-,"1,500",-,"1,500","1,200","1,280",...,"1,200","1,160","1,150","1,180",-,"1,500","1,180","1,160",-,"1,180"
2020-03-20 00:00:00,"1,239","1,310",-,"1,500",-,"1,500",-,"1,500","1,200",880,...,"1,200","1,160","1,150","1,180",-,"1,500","1,150","1,160",-,"1,180"
2020-03-23 00:00:00,"1,261","1,304",-,"1,500",-,"1,500",-,"1,500","1,200","1,280",...,"1,200","1,160","1,150","1,180",-,"1,500","1,150","1,330",-,"1,180"
2020-03-24 00:00:00,"1,261","1,300",-,"1,500",-,"1,500",-,"1,500","1,200","1,280",...,"1,200","1,160","1,150","1,180",-,"1,500","1,150","1,330",-,"1,180"
2020-03-25 00:00:00,"1,250","1,298",-,"1,500",-,"1,500",-,"1,500","1,200","1,280",...,"1,200","1,160","1,150","1,180",-,"1,500","1,150","1,330",-,"1,180"
2020-03-26 00:00:00,"1,297","1,295",-,"1,500",-,"1,500",-,"1,500","1,400","1,280",...,"1,400","1,160","1,200","1,180",-,"1,500","1,280","1,330",-,"1,180"
2020-03-27 00:00:00,"1,283","1,290",-,"1,500",-,"1,500",-,"1,500","1,400","1,180",...,"1,400","1,160","1,200","1,180",-,"1,500","1,280","1,330",-,"1,180"
2020-03-30 00:00:00,"1,283","1,287",-,"1,500",-,"1,500",-,"1,500","1,400",990,...,"1,200","1,160","1,200","1,280",-,"1,500","1,280","1,330",-,"1,180"
2020-03-31 00:00:00,"1,286","1,298",-,"1,500",-,"1,500",-,"1,500","1,400",990,...,"1,200","1,160","1,200","1,280",-,"1,500","1,280","1,330",-,"1,180"

In [57]:
moo.구분[51:]

51     제주
52    NaN
53    NaN
Name: 구분, dtype: object

In [66]:
moo.구분.unique()

array(['평균', '평년', '서울', '부산', '대구', '인천', '광주', '대전', '울산', '수원', '의정부',
       '춘천', '청주', '전주', '순천', '포항', '안동', '창원', '제주'], dtype=object)

In [65]:
# # 지역 (구분)
# moo.구분[2:13] = '서울' 
# moo.구분[13:17] = '부산' 
# moo.구분[17:21] = '대구' 
# moo.구분[21:24] = '인천' 
# moo.구분[24:27] = '광주' 
# moo.구분[27:31] = '대전' 
# moo.구분[31:33] = '울산' 
# moo.구분[33:36] = '수원' 
# moo.구분[37:39] = '춘천' 
# moo.구분[39:42] = '청주' 
# moo.구분[42:44] = '전주' 
# moo.구분[45:47] = '포항' 
# moo.구분[48:51] = '창원' 
# moo.구분[51:] = '제주'

In [30]:
# 삭제할 컬럼 선정 
dum_cols = moo.columns[1:3]
# 데이터 제거 
# 굳이 예외 처리를 하는 이유 => 
try:    
    moo.drop( dum_cols, inplace=True, axis=1 )
    print("columns 제거>>> \n", moo.head(2) )
except Exception as e:
    print('error => ',e) # 눈으로 확인이 가능하다

columns 제거>>>
    구분 2020-01-02 00:00:00 2020-01-05 00:00:00 2020-01-06 00:00:00  \
0  평균               1,287               1,287               1,303
1  평년               1,561               1,449               1,432

  2020-01-07 00:00:00 2020-01-08 00:00:00 2020-01-09 00:00:00  \
0               1,277               1,352               1,333
1               1,411               1,407               1,403

  2020-01-12 00:00:00 2020-01-13 00:00:00 2020-01-14 00:00:00  \
0               1,329               1,329               1,329
1               1,352               1,340               1,326

          ...         2020-03-18 00:00:00 2020-03-19 00:00:00  \
0         ...                       1,260               1,257
1         ...                       1,297               1,305

  2020-03-20 00:00:00 2020-03-23 00:00:00 2020-03-24 00:00:00  \
0               1,239               1,261               1,261
1               1,310               1,304               1,300

  2020-03-25 00:00:00 2020-03-26 00:00:00 2020-03-27 00:00:00  \
0               1,250               1,297               1,283
1               1,298               1,295               1,290

  2020-03-30 00:00:00 2020-03-31 00:00:00
0               1,283               1,286
1               1,287               1,298

[2 rows x 61 columns]